micronaut:

  application:
    name: agentOrchestrator

  server:
    port: 8080

  security:
    authentication: bearer
    enabled: false

  http:
    client:
      connect-timeout: 5s
---
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.ilunos.orchestrator.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#        show_sql: true
        bytecode:
          provider: none
